@startuml
!include <archimate/Archimate>

title Test Diagram

' Description: Generated ArchiMate diagram

left to right direction

' Elements
Business_Actor(test_element, "Test Element")


' Legend
legend right
  Business Layer
end legend

@enduml